### ISSUE TITLE
Got below error when running `sbt run`

### ISSUE THREAD

**Issue by yingdi11** [jbaysolutions/play-java-resumable#1]
[ERROR] Failed to construct terminal; falling back to unsupported
java.lang.NumberFormatException: For input string: "0x100"
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.lang.Integer.parseInt(Integer.java:580)
        at java.lang.Integer.valueOf(Integer.java:766)
        at jline.internal.InfoCmp.parseInfoCmp(InfoCmp.java:59)
        at jline.UnixTerminal.parseInfoCmp(UnixTerminal.java:233)
        at jline.UnixTerminal.<init>(UnixTerminal.java:64)
        at jline.UnixTerminal.<init>(UnixTerminal.java:49)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at java.lang.Class.newInstance(Class.java:442)
        at jline.TerminalFactory.getFlavor(TerminalFactory.java:209)
        at jline.TerminalFactory.create(TerminalFactory.java:100)
        at jline.TerminalFactory.get(TerminalFactory.java:184)
        at jline.TerminalFactory.get(TerminalFactory.java:190)
        at jline.console.ConsoleReader.<init>(ConsoleReader.java:240)
        at jline.console.ConsoleReader.<init>(ConsoleReader.java:232)
        at jline.console.ConsoleReader.<init>(ConsoleReader.java:220)
        at play.sbt.PlayConsoleInteractionMode$.withConsoleReader(PlayInteractionMode.scala:56)
        at play.sbt.PlayConsoleInteractionMode$.waitForKey(PlayInteractionMode.scala:60)
        at play.sbt.PlayConsoleInteractionMode$.waitForCancel(PlayInteractionMode.scala:83)
        at play.sbt.run.PlayRun$$anonfun$playRunTask$1$$anonfun$apply$2$$anonfun$apply$3.apply(PlayRun.scala:123)
        at play.sbt.run.PlayRun$$anonfun$playRunTask$1$$anonfun$apply$2$$anonfun$apply$3.apply(PlayRun.scala:53)
        at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
        at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
        at sbt.std.Transform$$anon$4.work(System.scala:63)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
        at sbt.Execute.work(Execute.scala:237)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
        at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
        at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

**Comment by gmsa** [comment]
Looks like a problem with your sbt: https://www.google.com/search?newwindow=1&sxsrf=ACYBGNTiyJtVeYOwYIEa9dnkRzq64Mw9cQ%3A1582015572589&ei=VKRLXvPCI5KmUOD6lugO&q=sbt+Failed+to+construct+terminal%3B+falling+back+to+unsupported&oq=sbt+Failed+to+construct+terminal%3B+falling+back+to+unsupported&gs_l=psy-ab.12..35i39j0i203j0i8i67j0i22i30l2.0.0..41894...0.0..0.139.233.1j1......0......gws-wiz.......0i7i30j0i8i30.T-EGYAEESVQ&ved=0ahUKEwjzvO6h29rnAhUSExQKHWC9Be0Q4dUDCAs
